name: homework_firebase_auth
description: "Homework firebase auth"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.10+1
  zoom_tap_animation: ^1.1.0
  loading_animation_widget: ^1.2.1
  email_otp: ^2.1.2
  firebase_crashlytics: ^3.5.6
  firebase_analytics: ^10.10.6
  path_provider: ^2.1.3
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
