// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADtu9FkKoFH7n_ZhcKnc4g913NrdWyhMQ',
    appId: '1:808429692116:web:fd0b826903605b994b8741',
    messagingSenderId: '808429692116',
    projectId: 'homework-firebase-auth-87652',
    authDomain: 'homework-firebase-auth-87652.firebaseapp.com',
    storageBucket: 'homework-firebase-auth-87652.appspot.com',
    measurementId: 'G-C5LR7CD44W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApzOMx_Z35QnPE3ZXmM_bypv6u3hf8Caw',
    appId: '1:808429692116:android:ad16876db40f24824b8741',
    messagingSenderId: '808429692116',
    projectId: 'homework-firebase-auth-87652',
    storageBucket: 'homework-firebase-auth-87652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMra886mFGQ_MXfXQpv8eSb8yUyxDohN4',
    appId: '1:808429692116:ios:4fd77297380da5fb4b8741',
    messagingSenderId: '808429692116',
    projectId: 'homework-firebase-auth-87652',
    storageBucket: 'homework-firebase-auth-87652.appspot.com',
    iosBundleId: 'com.pdp.homeworkFirebaseAuth',
  );
}
